### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by yomanx** [BenoitFreslon/Vibration#1]
Hi!

When i try to build i get this errors:
![Screen Shot 2019-04-16 at 17 03 47](https://user-images.githubusercontent.com/3980592/56216229-b79f1700-6069-11e9-903c-037ecc414d19.png)

**Comment by BenoitFreslon** [comment]
Hello,

Did you installed the iOS Build support on Unity?

Set the target to iOS then.

Maybe this doc will help you:
https://docs.unity3d.com/Manual/NativePlugins.html <https://docs.unity3d.com/Manual/NativePlugins.html>

Cheers,

Benoît

**Comment by yomanx** [comment]
Thanks!

Will it work with latest iOS? Vibration.Vibrate();

**Comment by BenoitFreslon** [comment]
OK it should works now.
