### ISSUE TITLE
Normal vibration not working on iOS 13.2.2

### ISSUE THREAD

**Issue by skoteskote** [BenoitFreslon/Vibration#10]
First of all, thanks for a great plugin! 

I recently upgraded to iOS 13.2.2 and now the normal "main" vibration is not working for some reason. Pop and the other haptics are working, but the classic default doesn't do anything. Any idea of what might cause this?

**Comment by BenoitFreslon** [comment]
Hello

Do you mean this method?
`Handheld.Vibrate();`

It's the normal vibration of Unity.

**Comment by skoteskote** [comment]
Hi! 

No, the main method: `Vibration.Vibrate ();`

When I build the example project the button assigned to that method doesn't do anything, but the pop, peek and nope vibrations does work. However, that method did work on previous versions of iOS.

**Comment by skoteskote** [comment]
Now it works again, thank you!
