### ISSUE TITLE
iOS build error Symbol: __VibrateNope

### ISSUE THREAD

**Issue by BenDevelopment** [BenoitFreslon/Vibration#11]
Hi!
First, thank you for your work!
I'm experiencing a problem when trying to build for iOS:

```
12720: ▸ ❌;  Undefined symbols for architecture armv7
12721: ▸ > Symbol: __VibrateNope
12722: ▸ > Referenced from: _Vibration__VibrateNope_mF571C84C03060C5EA2270E855DE9D7A0BA1832C5 in Assembly-CSharp1.o
12723: ▸ ❌;  ld: symbol(s) not found for architecture armv7
12724: ▸ ❌;  clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Everything works well with Android.

Any idea why I got this error? Am I missing something?

**Comment by BenoitFreslon** [comment]
Hello, did you include the Plugins/iOS in your Unity Project?

**Comment by Marcloure** [comment]
I'm getting a similar issue (sorry for being prints, I was working on a remote machine): 

![image](https://user-images.githubusercontent.com/29084710/89897279-284e3900-dbb5-11ea-8f01-83afab86368d.png)
![image](https://user-images.githubusercontent.com/29084710/89897346-3f8d2680-dbb5-11ea-8af1-63dde601a5c3.png)

**Comment by AnnKrepchenko** [comment]
Guys, try to reimport plugin, leaving checked all ios boxes

**Comment by Marcloure** [comment]
Just a late update, reimporting the package did solve my issue. Thank you.
