### ISSUE TITLE
Undefined symbol

### ISSUE THREAD

**Issue by fillmore-admin** [BenoitFreslon/Vibration#15]
Undefined symbol: __VibratePeek
Undefined symbol: __VibratePop
Undefined symbol: __VibrateNope
Undefined symbol: __Vibrate
Undefined symbol: __HasVibrator

Newly upgraded - Unity 2021.2.3f1 (Intel version from Unity hub)
Code worked in Unity 2019.x

xCode screenshot:
![image](https://user-images.githubusercontent.com/11894156/143505774-4cc40688-fcbd-4a95-bef9-0d925521877d.png)

**Comment by BenoitFreslon** [comment]
Works well on Unity 2021.2.19f
Import all files in your project.
