### ISSUE TITLE
Soften Vibration Power

### ISSUE THREAD

**Issue by unobatbayar** [BenoitFreslon/Vibration#16]
Thanks for the package! 

I love using `VibratePop()`, it's really smooth. But, is it possible to further soften the power? It's somewhat strong compared to vibration of iOS toggles. I checked the iOS plugin code and couldn't see anything that I can adjust.

I highly value any your reply.

**Comment by BenoitFreslon** [comment]
Hello, you want to adjust the VibratePop vibration on iOS?
Unfortunately you can't.
It uses native vibration of the iOS API.
```
+ (void)    vibratePop {
    AudioServicesPlaySystemSoundWithCompletion(1520, NULL); // Actuate `Pop` feedback (strong boom)
}
```
