### ISSUE TITLE
Does not compile for WEBGL builds.  

### ISSUE THREAD

**Issue by tristanjJC** [BenoitFreslon/Vibration#18]
Does not compile for WEBGL builds.  
line 174 should probably be removed
```
//Handheld.Vibrate ()
```
and 
line 222 needs an ifdef, probably this:
```
if (Application.isMobilePlatform)
            {
#if UNITY_ANDROID || UNITY_IOS
                Handheld.Vibrate();
#endif
            }
```

This is the error for reference
Vibration.cs(222,17): error CS0103: The name 'Handheld' does not exist in the current context

**Comment by vhnunes** [comment]
Fixed at #20
