### ISSUE TITLE
Where is the Unity package file?

### ISSUE THREAD

**Issue by andrewspalato** [BenoitFreslon/Vibration#21]
There are no releases or packages published. Am I missing something?
Is it possible we can import the package via package manager and GitHub URL?

**Comment by SH42913** [comment]
I'm working on it :)

**Comment by SH42913** [comment]
You can check this out
https://github.com/SH42913/Vibration/tree/unity-package
I will create PR later

**Comment by BenoitFreslon** [comment]
Added in the last version.
